### ISSUE TITLE
Use mouse buttons too

### ISSUE THREAD

**Issue by necauqua** [finestructure/Hummingbird#36]
Well, widely used drag/resize mechanic in some Linux WMs (and in windows with like altdrag app or similar) is button+mouse button, e.g. Win+LMB to drag and Win+RMB to resize.

I think it would be great if among the checkboxes for function keys there were also checkboxes for RMB and LMB, just because pure keybind dragging feels really odd to me (like there is no dragging, in a sense of moving the mouse with a button pressed).

Also yeah, just a question out of the issue scope: couldn't you just select the corner to be resized based on the quadrant where the mouse is relative to the window or is there some deeper issues I didn't find you talking about?

**Comment by necauqua** [comment]
I found out that this was your exact intent (this is kind of odd) when making this fork, however the idea of just including the possibility of that behavior is cool (not opposing but appending).

For me the original lacks featues like fn or option support and the metrics of this project, although I'd be using it for the time being for the drag I am so used to 🤷

**Comment by finestructure** [comment]
Hi @necauqua , thanks for opening the issue!

> I think it would be great if among the checkboxes for function keys there were also checkboxes for RMB and LMB

As you've discovered, this is something addressed by @dmarcotte's original project ["Easy-Move-Resize"](https://github.com/dmarcotte/easy-move-resize), which I originally wanted to extend with Hummingbird's functionality but ran into issues with. I'm afraid that mouse buttons as modifiers are definitely out of scope for Hummingbird because I feel this is well served by Daniel's project and it would be wrong to fork and then re-integrate original functionality. Sorry for the bad news! :)

Is there something you need that Easy-Move-Resize doesn't offer? It feels like between the two projects, all bases should be covered. I've also seen that EMR recently received Big Sur updates, so even if there's something you're missing it might be possible to add it. The project is actively being maintained.

> couldn't you just select the corner to be resized based on the quadrant where the mouse is relative to the window

This is actually a feature of Hummingbird since version 3.1:

![CleanShot 2021-03-24 at 06 19 31@2x](https://user-images.githubusercontent.com/65520/112259654-f338b780-8c68-11eb-864d-6cbccedd16af.png)

Hope that helps!

I'll go ahead and close the issue now but please don't hesitate to re-open it or raise a new one if you still have questions.
