### ISSUE TITLE
App stopped working all together all of a sudden

### ISSUE THREAD

**Issue by altryne** [finestructure/Hummingbird#47]
I'm not even sure how to test this, I had it working, upgraded to the latest macos and now nothing moves, I tried uninstalling and reinstalling and nothing moves. 

how can I debug this, I got so used to this ability that it's hard to imagine continuing working like this

**Comment by finestructure** [comment]
Hi @altryne , it definitely works on the latest macOS, that's what I'm running myself. Have you tried toggling the accessibility settings off and back on? That can behave weirdly when upgrading.

**Comment by altryne** [comment]
I have, several times, including removing it from that list completely and dragging it back in.

**Comment by finestructure** [comment]
Very strange. I presume you've tried changing the keyboard shortcuts just to rule out that it's actually working but somehow with different keys that you're used to?

And/or maybe try deleting the preferences in case something's broken there:

```
defaults delete co.finestructure.Hummingbird.prefs
```

**Comment by altryne** [comment]
This did it! removing preferences did the trick! Thank you ❤️ (paying right now, been using for free but this does it!)

**Comment by finestructure** [comment]
Glad to hear you got it working again!

**Comment by cacology** [comment]
FWIW The same thing just happened to me and the same solution worked: deleting preferences via the command line and `defaults`. But first I tried changing the keys in Hummingbird's Preferences (which didn't work) and also toggling  Accessibility (which also didn't work). My computer is managed by my Uni, so I wonder if they tweaked some setting somewhere.

[edit: made it clear I tried two things that didn't work first]

**Comment by finestructure** [comment]
Good to hear that this shakes things loose. It's unfortunate that this is such a black box and requires all these incantations to get it working :( I wish I had a better solution.

**Comment by cacology** [comment]
I wonder if it's some unexpected cache, or sandbox or something, that an infrequent update borks, but that gets rebuilt when the program writes a new preference file.

But, my submission is meant merely as more evidence: the solution will appear one day, or not.

**Comment by cacology** [comment]
Another possibility, which is obvious in retrospect, is that I hadn't registered it yet!

The software stopped working again, but on a different computer, but when I deleted the defaults it worked just fine. The only default that changed after deleting and re-setting everything is `firstLaunched`. Perhaps this is as designed, so that it only works 14 days without a license?

Maybe the actual issue is between the keyboard and the chair: the nudge to register doesn't look enough like a nudge. When the software stopped working, I thought that something was wrong, not that it was reminding me to register.

If this is working as designed, @finestructure , it might be easy enough to fix: just give the software a notice saying its not working right now without a license, but you can re-install or compile from source if you don't want to buy a license.

(I just purchased a license. I had downloaded the software via Homebrew, so that may also be part of the issue: I didn't see as much of your gentle encouragement to register until I started digging in GitHub to see if I could figure out what was wrong. This might be helpful to another user, who would benefit from the nudge, but who isn't in the habit of digging through GitHub. Life is busy and software that is working I can forget to donate to, even when I can.)

**Comment by finestructure** [comment]
Yes, resetting the preferences will also reset the 14 day trial period. Don't tell anyone ;)

I don't have the source code in front of me right now, but I'm pretty sure there is a dialog or something on next launch after the trial period expires. Since that typically only happens on restart (which may be rare on some/most Macs), perhaps the dialog box got lost in the startup noise?

**Comment by cacology** [comment]
Ah, yes, this would close the issue if it weren't already closed. All I can say is that I missed the nudge--if you want to work on that at some point, feel free to open another issue and tag me. I can remove the license, backdate, etc. and try to figure out what exactly went wrong.
